### ISSUE TITLE
Does not work with plotly

### ISSUE THREAD

**Issue by baggepinnen** [queryverse/ElectronDisplay.jl#63]
If I plot using Plotly as backend to Plots.jl, I get a new, empty, electrondisplay each time I plot, nothing is shown.

```julia
julia> plotly()
[ Info: For saving to png with the Plotly backend ORCA has to be installed.
Plots.PlotlyBackend()

julia> using ElectronDisplay

julia> plot(randn(10))
```

**Comment by davidanthoff** [comment]
We just started adding proper plotly support, so I'm going to close this here because this should work once we tag a new release. Would be great if you could try it once we push a new version.

**Comment by baggepinnen** [comment]
I tried on ElectronDisplay#master and I still have the same behavior, nothing is shown and a new window is opened for each call to `plot` with plotly as backend

**Comment by davidanthoff** [comment]
Yeah, this is not on ElectronDisplay#master, it is on https://github.com/julia-vscode/plotgallery `master`. It will flow here soon :)
